#!/usr/bin/env python

import sys

from rqt_virtual_joy.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'rqt_virtual_joy'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))